export const ACTION_TYPE = {
	SET_TODOS: 'SET_TODOS',
	LOADING_START: 'LOADING_START',
	LOADING_END: 'LOADING_END',
	ADD_TODO: 'ADD_TODO',
	EDIT_TODO: 'EDIT_TODO',
	REMOVE_TODO: 'REMOVE_TODO',
	UPDATE_TODO: 'UPDATE_TODO',
	SET_SEARCH_INPUT: 'SET_SEARCH_INPUT',
	SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
	SET_IS_SORTING_AZ: 'SET_IS_SORTING_AZ',
}





